=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="CourierType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="companyId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CompanyType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="couriers" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="courier" type="CourierType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="company" type="CompanyType"/>

</xs:schema>

=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/company.xml
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="company.xsd">

    <id>1</id>
    <name>Company A</name>
    <couriers>
        <courier>
            <id>1</id>
            <firstName>Bob</firstName>
            <lastName>Peterson</lastName>
            <companyId>1</companyId>
        </courier>
        <courier>
            <id>2</id>
            <firstName>Steven</firstName>
            <lastName>Anderson</lastName>
            <companyId>1</companyId>
        </courier>
        <courier>
            <id>3</id>
            <firstName>John</firstName>
            <lastName>Travis</lastName>
            <companyId>1</companyId>
        </courier>
        <courier>
            <id>4</id>
            <firstName>Tomas</firstName>
            <lastName>Orange</lastName>
            <companyId>1</companyId>
        </courier>
    </couriers>
</company>
