=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="orderDetails" type="xs:string"/>
            <xs:element name="courierId" type="xs:string"/>
            <xs:element name="customerId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DeliveryAddressType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="customerId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="orders" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="order" type="OrderType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="deliveryAddresses" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="deliveryAddress" type="DeliveryAddressType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="customer" type="CustomerType"/>

</xs:schema>

=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/customer.xml
<customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="customer.xsd">

    <id>1</id>
    <firstName>Tom</firstName>
    <lastName>Brown</lastName>
    <orders>
        <order>
            <id>1</id>
            <orderDetails>burger</orderDetails>
            <courierId>1</courierId>
            <customerId>1</customerId>
        </order>
        <order>
            <id>2</id>
            <orderDetails>pizza</orderDetails>
            <courierId>2</courierId>
            <customerId>1</customerId>
        </order>
        <order>
            <id>3</id>
            <orderDetails>sushi</orderDetails>
            <courierId>3</courierId>
            <customerId>1</customerId>
        </order>
    </orders>
    <deliveryAddresses>
        <deliveryAddress>
            <id>1</id>
            <address>Leeton Ridge Street,1</address>
            <customerId>1</customerId>
        </deliveryAddress>
        <deliveryAddress>
            <id>2</id>
            <address>Wellington Ave.,2</address>
            <customerId>1</customerId>
        </deliveryAddress>
    </deliveryAddresses>
</customer>
