=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/hierarchy.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="data" type="DataType"/>
    <xs:complexType name="CompanyType">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="company" type="CompanyType"/>

    <xs:complexType name="CourierType">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="last_name" type="xs:string"/>
            <xs:element name="company_id" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="courier" type="CourierType"/>

    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="last_name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="customer" type="CustomerType"/>

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="order_details" type="xs:string"/>
            <xs:element name="customer_id" type="xs:int"/>
            <xs:element name="courier_id" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="order" type="OrderType"/>

    <xs:complexType name="DeliveryAddressType">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="customer_id" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="delivery_address" type="DeliveryAddressType"/>

    <xs:complexType name="DataType">
        <xs:sequence>
            <xs:element name="company" type="CompanyType" maxOccurs="unbounded"/>
            <xs:element name="courier" type="CourierType" maxOccurs="unbounded"/>
            <xs:element name="customer" type="CustomerType" maxOccurs="unbounded"/>
            <xs:element name="delivery_address" type="DeliveryAddressType" maxOccurs="unbounded"/>
            <xs:element name="order" type="OrderType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== NataliiaGD/Java_Laba_Delivery_Service/src/main/resources/xml/hierarchy.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hierarchy.xsd">
    <company>
        <id>1</id>
        <name>Delivery_Company1</name>
    </company>
    <courier>
        <id>2</id>
        <first_name>Bob</first_name>
        <last_name>Peterson</last_name>
        <company_id>1</company_id>
    </courier>
    <customer>
        <id>1</id>
        <first_name>Tom</first_name>
        <last_name>Brown</last_name>
    </customer>
    <delivery_address>
        <id>2</id>
        <address>Wellington avenue</address>
        <customer_id>2</customer_id>
    </delivery_address>
    <order>
        <id>1</id>
        <order_details>burger</order_details>
        <customer_id>1</customer_id>
        <courier_id>2</courier_id>
    </order>

</data>
